[phases.setup]
nixPkgs = ['php81', 'php81Extensions.pdo', 'php81Extensions.pdo_sqlite']

[phases.install]
aptPkgs = ['nodejs', 'npm']
cmds = [
  'composer install --no-dev',
  'npm ci',
  'touch database/database.sqlite'
]

[phases.build]
cmds = [
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache',
  'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'