[phases.setup]
aptPkgs = [
    "php8.1",
    "php8.1-cli",
    "php8.1-common",
    "php8.1-sqlite3",
    "php8.1-xml",
    "php8.1-curl",
    "php8.1-mbstring",
    "php8.1-zip",
    "sqlite3",
    "nodejs",
    "npm"
]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "touch database/database.sqlite",
    "chmod -R 777 storage bootstrap/cache database"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"