[phases.setup]
nixPkgs = [
    "php81",
    "php81Extensions.pdo",
    "php81Extensions.pdo_sqlite",
    "php81Extensions.mbstring",
    "php81Extensions.xml",
    "php81Extensions.curl",
    "php81Extensions.zip",
    "php81Packages.composer",
    "nodejs_18",
    "sqlite"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "touch database/database.sqlite",
    "chmod -R 777 storage bootstrap/cache database"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"