[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.healthcheck]
path = "/up"
interval = "15s"
timeout = "5s"
retries = 3